name: Dependency Submission

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

jobs:
  submit-rust-workspace-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Submit Rust workspace dependency graph
        uses: advanced-security/component-detection-dependency-submission-action@v0.1.3
        with:
          filePath: .
          detector-name: rust-workspace-dependency-submission
          detector-version: 1.0.0
          detector-url: https://github.com/advanced-security/component-detection-dependency-submission-action
